export const NombComercialConsts = {
  SELINA_SJO: 'SELINA OPERATION SAN JOSE CITY S.A.',
  SELINA_JACO: 'SELINA OPERATION PLAYA JACO S.A.',
  SELINA_FORTUNA: 'SELINA OPERATION LA FORTUNA S.A.',
  SELINA_MONTEVERDE: 'SELINA OPERATION MONTEVERDE S.A.',
  SELINA_PVIEJO: 'SELINA OPERATION PUERTO VIEJO S.A.',
  SELINA_TAMARINDO: 'SELINA OPERATION TAMARINDO BEACH S.A.',
  SELINA_MANUEL_ANTONIO: 'HOTEL CASITAS ECLIPSE S.A.',
  SELINA_SANTA_TERESA: 'SELINA OPERATION SANTA TERESA S.A.',
  SELINA_NOSARA: 'SELINA OPERATIONS NOSARA SUNSETS S.A.'
};